import img from "../../images/new.png";

const dummy_products = [
  {
    _id: "p1",
    user: "user1",
    productName: "textEditor",
    image: img,
    brand: "NewBrand",
    description: "JATE",
    price: 250,
    countInStock: 5,
  },
  {
    _id: "p2",
    user: "user1",
    productName: "textEditor",
    image: img,
    brand: "NewBrand",
    description: "JATE",
    price: 250,
    countInStock: 5,
  },
  {
    _id: "p3",
    user: "user1",
    productName: "textEditor",
    image: img,
    brand: "NewBrand",
    description: "JATE",
    price: 250,
    countInStock: 5,
  },
  {
    _id: "p4",
    user: "user1",
    productName: "textEditor",
    image: img,
    brand: "NewBrand",
    description: "JATE",
    price: 250,
    countInStock: 5,
  },
  {
    _id: "p5",
    user: "user1",
    productName: "textEditor",
    image: img,
    brand: "NewBrand",
    description: "JATE",
    price: 250,
    countInStock: 5,
  },
  {
    _id: "p6",
    user: "user1",
    productName: "textEditor",
    image: img,
    brand: "NewBrand",
    description: "JATE",
    price: 250,
    countInStock: 5,
  },
  {
    _id: "p7",
    user: "user1",
    productName: "textEditor",
    image: img,
    brand: "NewBrand",
    description: "JATE",
    price: 250,
    countInStock: 5,
  },
];

export default dummy_products;
