import house from "../../images/house.jpg";
import shoes from "../../images/shoes.jpg";

const dummy_products = [
  {
    _id: "p1",
    user: "user1",
    productName: "5-bed room house",
    image: house,
    brand: "NewBrand",
    description: "JATE",
    price: "1,00,000",
    countInStock: 5,
  },
  {
    _id: "p2",
    user: "user1",
    productName: "Water proof shoes",
    image: shoes,
    brand: "NewBrand",
    description: "shoes",
    price: 250,
    countInStock: 5,
  },
  {
    _id: "p3",
    user: "user1",
    productName: "5-bed room house",
    image: house,
    brand: "NewBrand",
    description: "JATE",
    price: "1,00,000",
    countInStock: 5,
  },
  {
    _id: "p4",
    user: "user1",
    productName: "Water proof shoes",
    image: shoes,
    brand: "NewBrand",
    description: "shoes",
    price: 250,
    countInStock: 5,
  },
  {
    _id: "p5",
    user: "user1",
    productName: "5-bed room house",
    image: house,
    brand: "NewBrand",
    description: "JATE",
    price: "1,00,000",
    countInStock: 5,
  },
  {
    _id: "p6",
    user: "user1",
    productName: "Water proof shoes",
    image: shoes,
    brand: "NewBrand",
    description: "shoes",
    price: 250,
    countInStock: 5,
  },
  {
    _id: "p7",
    user: "user1",
    productName: "Water proof shoes",
    image: shoes,
    brand: "NewBrand",
    description: "shoes",
    price: "250",
    countInStock: 5,
  },
];

export default dummy_products;
