export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const UPDATE_USER = "UPDATE_USER";
export const USER_TO_STATE = "USER_TO_STATE";
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
